export const VOICE_LINES={
 opening:{speaker:'مرزوق',text:'لا تطلع يا بيسو... أنا بس أحاول أحميك',caption:'مرزوق: «لا تطلع يا بيسو... أنا بس أحاول أحميك»'},
 'resume-safe':{speaker:'بيسو',text:'رجعت عند آخر نقطة آمنة. مرزوق للحين يدور عليك.',caption:'رجعت عند آخر نقطة آمنة. مرزوق للحين يدور عليك.'},
 'touch-hint':{speaker:'النظام',text:'استخدم سحب الشاشة للنظر، وأزرار الحركة بالأسفل.',caption:'استخدم سحب الشاشة للنظر، وأزرار الحركة بالأسفل.'},
 'intro-after':{speaker:'بيسو',text:'مرزوق... وش سويت؟',caption:'بيسو: «مرزوق... وش سويت؟»'},
 'flash-missing':{speaker:'بيسو',text:'الفلاشلايت على الطاولة.',caption:'الفلاشلايت على الطاولة.'},
 'flash-empty':{speaker:'بيسو',text:'الفلاشلايت مات. بقي صوت المكان.',caption:'الفلاشلايت مات. بقي صوت المكان.'},
 'bag-missing':{speaker:'بيسو',text:'الشنطة عند مدخل المتاهة.',caption:'الشنطة عند مدخل المتاهة.'},
 'energy-used':{speaker:'بيسو',text:'رجعت رجول بيسو تشتغل.',caption:'رجعت رجول بيسو تشتغل.'},
 'almond-used':{speaker:'بيسو',text:'ماء اللوز رجّع شوية نور.',caption:'ماء اللوز رجّع شوية نور.'},
 'photo-back-reaction':{speaker:'بيسو',text:'لازم بيسو ينام قبل ما أقفل عليه. لو درى وش سويت، ما راح يسامحني... الخط خطه، والكذبة بعد كذبته.',caption:'بيسو: «الخط خطه... والكذبة بعد كذبته.»'},
 'pickup-flash':{speaker:'بيسو',text:'النور قليل... لازم أختار متى أشغله.',caption:'بيسو: «النور قليل... لازم أختار متى أشغله.»'},
 'pickup-key':{speaker:'بيسو',text:'المفتاح تحت السرير؟ يا سلام على الأمن.',caption:'بيسو: «المفتاح تحت السرير؟ يا سلام على الأمن.»'},
 'enter-maze':{speaker:'بيسو',text:'هذا المكان أكبر من اللي وصفه مرزوق.',caption:'بيسو: «هذا المكان أكبر من اللي وصفه مرزوق.»'},
 'pickup-battery':{speaker:'بيسو',text:'بطارية نادرة. عشرون ثانية زيادة.',caption:'بطارية نادرة. عشرون ثانية زيادة.'},
 'eat-mushroom':{speaker:'بيسو',text:'الغريب أنه نفع. رجعت الستامينا.',caption:'الغريب أنه نفع. رجعت الستامينا.'},
 'pickup-bag':{speaker:'بيسو',text:'شنطة خفيفة. افتحها بزر بي.',caption:'شنطة خفيفة. افتحها بزر B.'},
 'need-bag':{speaker:'بيسو',text:'أحتاج الشنطة قبل أشيل هذا.',caption:'أحتاج الشنطة قبل أشيل هذا.'},
 'store-energy':{speaker:'بيسو',text:'حفظت مشروب الطاقة في الشنطة.',caption:'حفظت مشروب الطاقة في الشنطة.'},
 'store-almond':{speaker:'بيسو',text:'حفظت ماء اللوز في الشنطة.',caption:'حفظت ماء اللوز في الشنطة.'},
 'breaker-wrong':{speaker:'بيسو',text:'العداد هادي. العطل في جهة ثانية.',caption:'العداد هادي. العطل في جهة ثانية.'},
 'monitor-ended':{speaker:'بيسو',text:'التسجيل انتهى عند لحظة ظهور مرزوق خلف الكاميرا.',caption:'التسجيل انتهى عند لحظة ظهور مرزوق خلف الكاميرا.'},
 'vending-ended':{speaker:'بيسو',text:'الآلة أخذت قرارها.',caption:'الآلة أخذت قرارها.'},
 'vending-battery':{speaker:'بيسو',text:'نزلت بطارية بدل المشروب. تمشي.',caption:'نزلت بطارية بدل المشروب. تمشي.'},
 'vending-rat':{speaker:'بيسو',text:'طلع فأر. الآلة واضحة في سياستها.',caption:'طلع فأر. الآلة واضحة في سياستها.'},
 'locker-noise':{speaker:'بيسو',text:'صرير الخزانة فضح المكان كله.',caption:'صرير الخزانة فضح المكان كله.'},
 bunny:{speaker:'بيسو',text:'دبدوب؟ هنا؟ ...ليش ما تفاجئني.',caption:'بيسو: «دبدوب؟ هنا؟ ...ليش ما تفاجئني.»'},
 'bunny-again':{speaker:'بيسو',text:'للحين هنا يا صديقي.',caption:'بيسو: «للحين هنا يا صديقي.»'},
 tv:{speaker:'بيسو',text:'حتى التلفزيون مقطوع عنه الكهربا.',caption:'بيسو: «حتى التلفزيون مقطوع عنه الكهربا.»'},
 'letter-found':{speaker:'بيسو',text:'الدليل الأول معي. بقي التسجيل قرب الاستراحة عشان أوصل للهروب الحقيقي.',caption:'الدليل الأول معك. بقي التسجيل قرب الاستراحة للوصول للهروب الحقيقي.'},
 'exit-voice':{speaker:'مرزوق',text:'افتح لي يا بيسو. أقدر أفسّر لك.',caption:'مرزوق من خلف الباب: «افتح لي يا بيسو. أقدر أفسّر لك.»'},
 retry:{speaker:'بيسو',text:'رجعت للنقطة الآمنة. لازم أطفي النور وأكسر خط النظر.',caption:'رجعت للنقطة الآمنة. طفّ النور واكسر خط النظر.'},
 'blackout-again':{speaker:'بيسو',text:'رجع الظلام. علامة العداد ظهرت من جديد.',caption:'رجع الظلام. علامة العداد ظهرت من جديد.'},
 'power-manual':{speaker:'بيسو',text:'اشتغلت الكهرباء قبل رجوعها التلقائي.',caption:'اشتغلت الكهرباء قبل رجوعها التلقائي.'},
 'power-auto':{speaker:'بيسو',text:'رجعت الكهرباء بعد ثلاث دقائق.',caption:'رجعت الكهرباء بعد ثلاث دقائق.'},
 'event-blackout-0':{speaker:'النظام',text:'انطفأت كل اللمبات.',caption:'انطفأت كل اللمبات.'},
 'event-blackout-1':{speaker:'مرزوق',text:'الحين بتسمع المكان مثل ما أسمعه.',caption:'مرزوق: «الحين بتسمع المكان مثل ما أسمعه.»'},
 'event-cctv-0':{speaker:'النظام',text:'التسجيل يظهر مرزوق واقفًا خلف الكاميرا.',caption:'التسجيل يظهر مرزوق واقفًا خلف الكاميرا.'},
 'event-cctv-1':{speaker:'مرزوق',text:'إذا شفتني هنا... لا تلتفت.',caption:'مرزوق: «إذا شفتني هنا... لا تلتفت.»'},
 'event-false-exit-0':{speaker:'النظام',text:'وراء باب إكزت غرفة ضيقة ومروحة فقط.',caption:'وراء باب EXIT غرفة ضيقة ومروحة فقط.'},
 'event-false-exit-1':{speaker:'بيسو',text:'حتى المخرج هنا يحتاج مخرج.',caption:'بيسو: «حتى المخرج هنا يحتاج مخرج.»'},
 'event-lounge-0':{speaker:'النظام',text:'الإضاءة هادئة أكثر من اللازم.',caption:'الإضاءة هادئة أكثر من اللازم.'},
 'event-lounge-1':{speaker:'مرزوق',text:'خذ راحتك... أعرف وينك.',caption:'صوت مرزوق من السماعة: «خذ راحتك... أعرف وينك.»'},
 checkpoint:{speaker:'بيسو',text:'نقطة آمنة. هنا تحفظ اللعبة. التسجيل قريب، وافتح دفتر إن عشان تعرف النهايات.',caption:'نقطة آمنة · هنا تحفظ اللعبة. التسجيل قريب؛ افتح دفتر N لمعرفة النهايات.'},
 'intro-silence':{speaker:'النظام',text:'وبعدين سكت كل شيء.',caption:'...وبعدين سكت كل شيء.'},
 'battery-zero':{speaker:'بيسو',text:'خلاص... صار لازم أسمع أكثر مما أشوف.',caption:'بيسو: «خلاص... صار لازم أسمع أكثر مما أشوف.»'},
 comedy:{speaker:'مرزوق',text:'أنت سريع... بس الممرات معي.',caption:'مرزوق: «أنت سريع... بس الممرات معي.»'},
 photo0:{speaker:'بيسو',text:'أول ما جيت، صب لي فنجال. قال: القهوة هالمرة على حسابي.'},
 photo1:{speaker:'بيسو',text:'عقب القهوة، ثقلت عيوني وأنا أطالع الساعة. مرزوق كان يطالع الباب.'},
 photo2:{speaker:'بيسو',text:'آخر شيء أذكره، صوت الباب وهو يتقفل. ومرزوق يقول إنه يحميني.'},
 recording:{speaker:'مرزوق',text:'بيسو، أنا حطّيت لك المنوّم وقفلت عليك... الممرات طلبت واحد بدالي. قلت لنفسي إني أحميك، بس كنت أحمي نفسي. رقم التجربة: بيسو. صاحب المشروع لا يتذكر.'},
 spotted:{speaker:'مرزوق',text:'شفت نورك يا بيسو... لا تركض.'},
 'spotted-light':{speaker:'مرزوق',text:'ترّك أعميتنا يا رجّال!'},
 'spotted-dark':{speaker:'مرزوق',text:'تعال تعال... تره ما بوه لسعة فلفلة هنا.'},
 lost:{speaker:'مرزوق',text:'اختفيت؟ ما راح تبعد.'},
 'puzzle-success':{speaker:'النظام',text:'طق! انفتح مزلاج الذكريات.'},
 'puzzle-fail':{speaker:'بيسو',text:'مو كذا... القهوة أولًا. وش صار بعدها؟'},
 'ending-truth':{speaker:'بيسو',text:'أنت ما لك حق تختار عني.'},
 'ending-comedy':{speaker:'مرزوق',text:'هذه المرة ما فيه منوّم... غالبًا.'},
 'ending-loop':{speaker:'بيسو',text:'أنت شخص رهيب يا مرزوق.'},
 'ending-secret':{speaker:'بيسو',text:'كان يكفي تقول لي الحقيقة.'}
};

export const VOICE_BY_CAPTION=Object.fromEntries(Object.entries(VOICE_LINES).filter(([,line])=>line.caption).map(([name,line])=>[line.caption,name]));

export const ROOM_VOICES=['opening','resume-safe','touch-hint','intro-after','flash-missing','flash-empty','energy-used','almond-used','photo-back-reaction','pickup-flash','pickup-key','photo0','photo1','photo2','intro-silence','puzzle-success','puzzle-fail'];
export const MAZE_VOICES=Object.keys(VOICE_LINES).filter(name=>!ROOM_VOICES.includes(name)&&!name.startsWith('ending-'));
